---

- name: Download and install helm
  script: ../files/install_helm.sh


- name: Create Helm namespace
  shell: kubectl create ns kube-tiller

- name: Create Helm service-account
  shell: kubectl create serviceaccount tiller --namespace kube-tiller

- name: Create Helm ClusterRoleBinding
  shell: 
    cmd: |
      cat << EOF | kubectl create -f -
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-tiller
      EOF

- name: Helm init
  shell: /usr/local/bin/helm init --service-account tiller --tiller-namespace kube-tiller 
